CREATE TABLE "mercedes_benz_make_and_model_tbl" (
    "make_and_model_id" serial   NOT NULL,
    "make" VARCHAR(200)   NOT NULL,
    "model" VARCHAR(200)   NOT NULL,
    "autoscout_url_make" VARCHAR(200)   NOT NULL,
    "autoscout_url_model" VARCHAR(200)   NOT NULL,
    CONSTRAINT "pk_mercedes_benz_make_and_model_tbl" PRIMARY KEY (
        "make_and_model_id"
     )
);

INSERT INTO mercedes_benz_make_and_model_tbl (make, model, autoscout_url_make, autoscout_url_model)
VALUES
    ('Mercedes Benz', '170', 'mercedes-benz', '170'),
    ('Mercedes Benz', '180', 'mercedes-benz', '180'),
    ('Mercedes Benz', '190', 'mercedes-benz', '190'),
    ('Mercedes Benz', '200', 'mercedes-benz', '200'),
    ('Mercedes Benz', '208', 'mercedes-benz', '208'),
    ('Mercedes Benz', '210/310', 'mercedes-benz', '210%2F310'),
    ('Mercedes Benz', '220', 'mercedes-benz', '220'),
    ('Mercedes Benz', '230', 'mercedes-benz', '230'),
    ('Mercedes Benz', '240', 'mercedes-benz', '240'),
    ('Mercedes Benz', '250', 'mercedes-benz', '250'),
    ('Mercedes Benz', '260', 'mercedes-benz', '260'),
    ('Mercedes Benz', '270', 'mercedes-benz', '270'),
    ('Mercedes Benz', '280', 'mercedes-benz', '280'),
    ('Mercedes Benz', '300', 'mercedes-benz', '300'),
    ('Mercedes Benz', '308', 'mercedes-benz', '308'),
    ('Mercedes Benz', '320', 'mercedes-benz', '320'),
    ('Mercedes Benz', '350', 'mercedes-benz', '350'),
    ('Mercedes Benz', '380', 'mercedes-benz', '380'),
    ('Mercedes Benz', '400', 'mercedes-benz', '400'),
    ('Mercedes Benz', '416', 'mercedes-benz', '416'),
    ('Mercedes Benz', '420', 'mercedes-benz', '420'),
    ('Mercedes Benz', '450', 'mercedes-benz', '450'),
    ('Mercedes Benz', '500', 'mercedes-benz', '500'),
    ('Mercedes Benz', '560', 'mercedes-benz', '560'),
    ('Mercedes Benz', '600', 'mercedes-benz', '600'),
    ('Mercedes Benz', 'Actros', 'mercedes-benz', 'actros'),
    ('Mercedes Benz', 'AMG GT', 'mercedes-benz', 'amg-gt'),
    ('Mercedes Benz', 'Atego', 'mercedes-benz', 'atego'),
    ('Mercedes Benz', 'CE 200', 'mercedes-benz', 'ce-200'),
    ('Mercedes Benz', 'CE 220', 'mercedes-benz', 'ce-220'),
    ('Mercedes Benz', 'CE 230', 'mercedes-benz', 'ce-230'),
    ('Mercedes Benz', 'CE 280', 'mercedes-benz', 'ce-280'),
    ('Mercedes Benz', 'CE 300', 'mercedes-benz', 'ce-300'),
    ('Mercedes Benz', 'Citan', 'mercedes-benz', 'citan'),
    ('Mercedes Benz', 'CL', 'mercedes-benz', 'cl'),
    ('Mercedes Benz', 'CL 160', 'mercedes-benz', 'cl-160'),
    ('Mercedes Benz', 'CL 180', 'mercedes-benz', 'cl-180'),
    ('Mercedes Benz', 'CL 200', 'mercedes-benz', 'cl-200'),
    ('Mercedes Benz', 'CL 220', 'mercedes-benz', 'cl-220'),
    ('Mercedes Benz', 'CL 230', 'mercedes-benz', 'cl-230'),
    ('Mercedes Benz', 'CL 320', 'mercedes-benz', 'cl-320'),
    ('Mercedes Benz', 'CL 420', 'mercedes-benz', 'cl-420'),
    ('Mercedes Benz', 'CL 500', 'mercedes-benz', 'cl-500'),
    ('Mercedes Benz', 'CL 55 AMG', 'mercedes-benz', 'cl-55-amg'),
    ('Mercedes Benz', 'CL 600', 'mercedes-benz', 'cl-600'),
    ('Mercedes Benz', 'CL 63 AMG', 'mercedes-benz', 'cl-63-amg'),
    ('Mercedes Benz', 'CL 65 AMG', 'mercedes-benz', 'cl-65-amg'),
    ('Mercedes Benz', 'CLA 180', 'mercedes-benz', 'cla-180'),
    ('Mercedes Benz', 'CLA 200', 'mercedes-benz', 'cla-200'),
    ('Mercedes Benz', 'CLA 220', 'mercedes-benz', 'cla-220'),
    ('Mercedes Benz', 'CLA 250', 'mercedes-benz', 'cla-250'),
    ('Mercedes Benz', 'CLA 35 AMG', 'mercedes-benz', 'cla-35-amg'),
    ('Mercedes Benz', 'CLA 45 AMG', 'mercedes-benz', 'cla-45-amg'),
    ('Mercedes Benz', 'A 140', 'mercedes-benz', 'a-140'),
    ('Mercedes Benz', 'A 150', 'mercedes-benz', 'a-150'),
    ('Mercedes Benz', 'A 160', 'mercedes-benz', 'a-160'),
    ('Mercedes Benz', 'A 170', 'mercedes-benz', 'a-170'),
    ('Mercedes Benz', 'A 180', 'mercedes-benz', 'a-180'),
    ('Mercedes Benz', 'A 190', 'mercedes-benz', 'a-190'),
    ('Mercedes Benz', 'A 200', 'mercedes-benz', 'a-200'),
    ('Mercedes Benz', 'A 210', 'mercedes-benz', 'a-210'),
    ('Mercedes Benz', 'A 220', 'mercedes-benz', 'a-220'),
    ('Mercedes Benz', 'A 250', 'mercedes-benz', 'a-250'),
    ('Mercedes Benz', 'A 35 AMG', 'mercedes-benz', 'a-35-amg'),
    ('Mercedes Benz', 'A 45 AMG', 'mercedes-benz', 'a-45-amg'),
    ('Mercedes Benz', 'B 150', 'mercedes-benz', 'b-150'),
    ('Mercedes Benz', 'B 160', 'mercedes-benz', 'b-160'),
    ('Mercedes Benz', 'B 170', 'mercedes-benz', 'b-170'),
    ('Mercedes Benz', 'B 180', 'mercedes-benz', 'b-180'),
    ('Mercedes Benz', 'B 200', 'mercedes-benz', 'b-200'),
    ('Mercedes Benz', 'B 250', 'mercedes-benz', 'b-250'),
    ('Mercedes Benz', 'B Electic Drive', 'mercedes-benz', 'b-electric-drive'),
    ('Mercedes Benz', 'C 160', 'mercedes-benz', 'c-160'),
    ('Mercedes Benz', 'C 180', 'mercedes-benz', 'c-180'),
    ('Mercedes Benz', 'C 200', 'mercedes-benz', 'c-200'),
    ('Mercedes Benz', 'C 220', 'mercedes-benz', 'c-220'),
    ('Mercedes Benz', 'C 230', 'mercedes-benz', 'c-230'),
    ('Mercedes Benz', 'C 240', 'mercedes-benz', 'c-240'),
    ('Mercedes Benz', 'C 250', 'mercedes-benz', 'c-250'),
    ('Mercedes Benz', 'C 270', 'mercedes-benz', 'c-270'),
    ('Mercedes Benz', 'C 280', 'mercedes-benz', 'c-280'),
    ('Mercedes Benz', 'C 30 AMG', 'mercedes-benz', 'c-30-amg'),
    ('Mercedes Benz', 'C 300', 'mercedes-benz', 'c-300'),
    ('Mercedes Benz', 'C 32 AMG', 'mercedes-benz', 'c-32-amg'),
    ('Mercedes Benz', 'C 320', 'mercedes-benz', 'c-320'),
    ('Mercedes Benz', 'C 350', 'mercedes-benz', 'c-350'),
    ('Mercedes Benz', 'C 36 AMG', 'mercedes-benz', 'c-36-amg'),
    ('Mercedes Benz', 'C 400', 'mercedes-benz', 'c-400'),
    ('Mercedes Benz', 'C 43 AMG', 'mercedes-benz', 'c-43-amg'),
    ('Mercedes Benz', 'C 450', 'mercedes-benz', 'c-450'),
    ('Mercedes Benz', 'C 55 AMG', 'mercedes-benz', 'c-55-amg'),
    ('Mercedes Benz', 'C 63 AMG', 'mercedes-benz', 'c-63-amg'),
    ('Mercedes Benz', 'E 200', 'mercedes-benz', 'e-200'),
    ('Mercedes Benz', 'E 220', 'mercedes-benz', 'e-220'),
    ('Mercedes Benz', 'E 230', 'mercedes-benz', 'e-230'),
    ('Mercedes Benz', 'E 240', 'mercedes-benz', 'e-240'),
    ('Mercedes Benz', 'E 250', 'mercedes-benz', 'e-250'),
    ('Mercedes Benz', 'E 260', 'mercedes-benz', 'e-260'),
    ('Mercedes Benz', 'E 270', 'mercedes-benz', 'e-270'),
    ('Mercedes Benz', 'E 280', 'mercedes-benz', 'e-280'),
    ('Mercedes Benz', 'E 290', 'mercedes-benz', 'e-290'),
    ('Mercedes Benz', 'E 300', 'mercedes-benz', 'e-300'),
    ('Mercedes Benz', 'E 320', 'mercedes-benz', 'e-320'),
    ('Mercedes Benz', 'E 350', 'mercedes-benz', 'e-350'),
    ('Mercedes Benz', 'E 36 AMG', 'mercedes-benz', 'e-36-amg'),
    ('Mercedes Benz', 'E 400', 'mercedes-benz', 'e-400'),
    ('Mercedes Benz', 'E 420', 'mercedes-benz', 'e-420'),
    ('Mercedes Benz', 'E 43 AMG', 'mercedes-benz', 'e-43-amg'),
    ('Mercedes Benz', 'E 430', 'mercedes-benz', 'e-430'),
    ('Mercedes Benz', 'E 450', 'mercedes-benz', 'e-450'),
    ('Mercedes Benz', 'E 50 AMG', 'mercedes-benz', 'e-50-amg'),
    ('Mercedes Benz', 'E 500', 'mercedes-benz', 'e-500'),
    ('Mercedes Benz', 'E 53 AMG', 'mercedes-benz', 'e-53-amg'),
    ('Mercedes Benz', 'E 55 AMG', 'mercedes-benz', 'e-55-amg'),
    ('Mercedes Benz', 'E 550', 'mercedes-benz', 'e-550'),
    ('Mercedes Benz', 'E 60 AMG', 'mercedes-benz', 'e-60-amg'),
    ('Mercedes Benz', 'E 63 AMG', 'mercedes-benz', 'e-63-amg'),
    ('Mercedes Benz', 'EQA', 'mercedes-benz', 'eqa'),
    ('Mercedes Benz', 'EQA 250', 'mercedes-benz', 'eqa-250'),
    ('Mercedes Benz', 'EQA 300', 'mercedes-benz', 'eqa-300'),
    ('Mercedes Benz', 'EQA 350', 'mercedes-benz', 'eqa-350'),
    ('Mercedes Benz', 'EQB 250', 'mercedes-benz', 'eqb-250'),
    ('Mercedes Benz', 'EQB 300', 'mercedes-benz', 'eqb-300'),
    ('Mercedes Benz', 'EQB 350', 'mercedes-benz', 'eqb-350'),
    ('Mercedes Benz', 'EQC 400', 'mercedes-benz', 'eqc-400'),
    ('Mercedes Benz', 'EQE 300', 'mercedes-benz', 'eqe-300'),
    ('Mercedes Benz', 'EQE 350', 'mercedes-benz', 'eqe-350'),
    ('Mercedes Benz', 'EQE 43', 'mercedes-benz', 'eqe-43'),
    ('Mercedes Benz', 'EQE 500', 'mercedes-benz', 'eqe-500'),
    ('Mercedes Benz', 'EQE 53', 'mercedes-benz', 'eqe-53'),
    ('Mercedes Benz', 'EQE SUV', 'mercedes-benz', 'eqe-suv'),
    ('Mercedes Benz', 'EQS', 'mercedes-benz', 'eqs'),
    ('Mercedes Benz', 'EQS SUV', 'mercedes-benz', 'eqs-suv'),
    ('Mercedes Benz', 'EQV 250', 'mercedes-benz', 'eqv-250'),
    ('Mercedes Benz', 'EQV 300', 'mercedes-benz', 'eqv-300'),
    ('Mercedes Benz', 'G', 'mercedes-benz', 'g'),
    ('Mercedes Benz', 'G 230', 'mercedes-benz', 'g-230'),
    ('Mercedes Benz', 'G 240', 'mercedes-benz', 'g-240'),
    ('Mercedes Benz', 'G 250', 'mercedes-benz', 'g-250'),
    ('Mercedes Benz', 'G 270', 'mercedes-benz', 'g-270'),
    ('Mercedes Benz', 'G 280', 'mercedes-benz', 'g-280'),
    ('Mercedes Benz', 'G 290', 'mercedes-benz', 'g-290'),
    ('Mercedes Benz', 'G 300', 'mercedes-benz', 'g-300'),
    ('Mercedes Benz', 'G 320', 'mercedes-benz', 'g-320'),
    ('Mercedes Benz', 'G 350', 'mercedes-benz', 'g-350'),
    ('Mercedes Benz', 'G 400', 'mercedes-benz', 'g-400'),
    ('Mercedes Benz', 'G 500', 'mercedes-benz', 'g-500'),
    ('Mercedes Benz', 'G 55 AMG', 'mercedes-benz', 'g-55-amg'),
    ('Mercedes Benz', 'G 63 AMG', 'mercedes-benz', 'g-63-amg'),
    ('Mercedes Benz', 'G 65 AMG', 'mercedes-benz', 'g-65-amg'),
    ('Mercedes Benz', 'G 650', 'mercedes-benz', 'g-650'),
    ('Mercedes Benz', 'ML 230', 'mercedes-benz', 'ml-230'),
    ('Mercedes Benz', 'ML 250', 'mercedes-benz', 'ml-250'),
    ('Mercedes Benz', 'ML 270', 'mercedes-benz', 'ml-270'),
    ('Mercedes Benz', 'ML 280', 'mercedes-benz', 'ml-280'),
    ('Mercedes Benz', 'ML 300', 'mercedes-benz', 'ml-300'),
    ('Mercedes Benz', 'ML 320', 'mercedes-benz', 'ml-320'),
    ('Mercedes Benz', 'ML 350', 'mercedes-benz', 'ml-350'),
    ('Mercedes Benz', 'ML 400', 'mercedes-benz', 'ml-400'),
    ('Mercedes Benz', 'ML 420', 'mercedes-benz', 'ml-420'),
    ('Mercedes Benz', 'ML 430', 'mercedes-benz', 'ml-430'),
    ('Mercedes Benz', 'ML 450', 'mercedes-benz', 'ml-450'),
    ('Mercedes Benz', 'ML 500', 'mercedes-benz', 'ml-500'),
    ('Mercedes Benz', 'ML 55 AMG', 'mercedes-benz', 'ml-55-amg'),
    ('Mercedes Benz', 'ML 63 AMG', 'mercedes-benz', 'ml-63-amg'),
    ('Mercedes Benz', 'R 280', 'mercedes-benz', 'r-280'),
    ('Mercedes Benz', 'R 300', 'mercedes-benz', 'r-300'),
    ('Mercedes Benz', 'R 320', 'mercedes-benz', 'r-320'),
    ('Mercedes Benz', 'R 350', 'mercedes-benz', 'r-350'),
    ('Mercedes Benz', 'R 500', 'mercedes-benz', 'r-500'),
    ('Mercedes Benz', 'R 63 AMG', 'mercedes-benz', 'r-63-amg'),
    ('Mercedes Benz', 'S 250', 'mercedes-benz', 's-250'),
    ('Mercedes Benz', 'S 260', 'mercedes-benz', 's-260'),
    ('Mercedes Benz', 'S 280', 'mercedes-benz', 's-280'),
    ('Mercedes Benz', 'S 300', 'mercedes-benz', 's-300'),
    ('Mercedes Benz', 'S 320', 'mercedes-benz', 's-320'),
    ('Mercedes Benz', 'S 350', 'mercedes-benz', 's-350'),
    ('Mercedes Benz', 'S 380', 'mercedes-benz', 's-380'),
    ('Mercedes Benz', 'S 400', 'mercedes-benz', 's-400'),
    ('Mercedes Benz', 'S 420', 'mercedes-benz', 's-420'),
    ('Mercedes Benz', 'S 430', 'mercedes-benz', 's-430'),
    ('Mercedes Benz', 'S 450', 'mercedes-benz', 's-450'),
    ('Mercedes Benz', 'S 500', 'mercedes-benz', 's-500'),
    ('Mercedes Benz', 'S 55 AMG', 'mercedes-benz', 's-55-amg'),
    ('Mercedes Benz', 'S 550', 'mercedes-benz', 's-550'),
    ('Mercedes Benz', 'S 560', 'mercedes-benz', 's-560'),
    ('Mercedes Benz', 'S 560 E', 'mercedes-benz', 's-560-e'),
    ('Mercedes Benz', 'S 580', 'mercedes-benz', 's-580'),
    ('Mercedes Benz', 'S 600', 'mercedes-benz', 's-600'),
    ('Mercedes Benz', 'S 63 AMG', 'mercedes-benz', 's-63-amg'),
    ('Mercedes Benz', 'S 650', 'mercedes-benz', 's-650'),
    ('Mercedes Benz', 'S 680', 'mercedes-benz', 's-680'),
    ('Mercedes Benz', 'Classe T', 'mercedes-benz', 'classe-t'),
    ('Mercedes Benz', 'V', 'mercedes-benz', 'v'),
    ('Mercedes Benz', 'V 200', 'mercedes-benz', 'v-200'),
    ('Mercedes Benz', 'V 220', 'mercedes-benz', 'v-220'),
    ('Mercedes Benz', 'V 230', 'mercedes-benz', 'v-230'),
    ('Mercedes Benz', 'V 250', 'mercedes-benz', 'v-250'),
    ('Mercedes Benz', 'V 280', 'mercedes-benz', 'v-280'),
    ('Mercedes Benz', 'V 300', 'mercedes-benz', 'v-300'),
    ('Mercedes Benz', 'X 220', 'mercedes-benz', 'x-220'),
    ('Mercedes Benz', 'X 250', 'mercedes-benz', 'x-250'),
    ('Mercedes Benz', 'X 350', 'mercedes-benz', 'x-350'),
    ('Mercedes Benz', 'CLC', 'mercedes-benz', 'clc'),
    ('Mercedes Benz', 'CLE ', 'mercedes-benz', 'cle'),
    ('Mercedes Benz', 'CLE 200', 'mercedes-benz', 'cle-200'),
    ('Mercedes Benz', 'CLE 220', 'mercedes-benz', 'cle-220'),
    ('Mercedes Benz', 'CLE 300', 'mercedes-benz', 'cle-300'),
    ('Mercedes Benz', 'CLK ', 'mercedes-benz', 'clk'),
    ('Mercedes Benz', 'CLK 200', 'mercedes-benz', 'clk-200'),
    ('Mercedes Benz', 'CLK 220', 'mercedes-benz', 'clk-220'),
    ('Mercedes Benz', 'CLK 230', 'mercedes-benz', 'clk-230'),
    ('Mercedes Benz', 'CLK 240', 'mercedes-benz', 'clk-240'),
    ('Mercedes Benz', 'CLK 270', 'mercedes-benz', 'clk-270'),
    ('Mercedes Benz', 'CLK 280', 'mercedes-benz', 'clk-280'),
    ('Mercedes Benz', 'CLK 320', 'mercedes-benz', 'clk-320'),
    ('Mercedes Benz', 'CLK 350', 'mercedes-benz', 'clk-350'),
    ('Mercedes Benz', 'CLK 430', 'mercedes-benz', 'clk-430'),
    ('Mercedes Benz', 'CLK 500', 'mercedes-benz', 'clk-500'),
    ('Mercedes Benz', 'CLK 55 AMG', 'mercedes-benz', 'clk-55-amg'),
    ('Mercedes Benz', 'CLK 63 AMG', 'mercedes-benz', 'clk-63-amg'),
    ('Mercedes Benz', 'CLS', 'mercedes-benz', 'cls'),
    ('Mercedes Benz', 'CLS 220', 'mercedes-benz', 'cls-220'),
    ('Mercedes Benz', 'CLS 250', 'mercedes-benz', 'cls-250'),
    ('Mercedes Benz', 'CLS 280', 'mercedes-benz', 'cls-280'),
    ('Mercedes Benz', 'CLS 300', 'mercedes-benz', 'cls-300'),
    ('Mercedes Benz', 'CLS 320', 'mercedes-benz', 'cls-320'),
    ('Mercedes Benz', 'CLS 350', 'mercedes-benz', 'cls-350'),
    ('Mercedes Benz', 'CLS 400', 'mercedes-benz', 'cls-400'),
    ('Mercedes Benz', 'CLS 450', 'mercedes-benz', 'cls-450'),
    ('Mercedes Benz', 'CLS 500', 'mercedes-benz', 'cls-500'),
    ('Mercedes Benz', 'CLS 53 AMG', 'mercedes-benz', 'cls-53-amg'),
    ('Mercedes Benz', 'CLS 63 AMG', 'mercedes-benz', 'cls-63-amg'),
    ('Mercedes Benz', 'GL 320', 'mercedes-benz', 'gl-320'),
    ('Mercedes Benz', 'GL 350', 'mercedes-benz', 'gl-350'),
    ('Mercedes Benz', 'GL 400', 'mercedes-benz', 'gl-400'),
    ('Mercedes Benz', 'GL 420', 'mercedes-benz', 'gl-420'),
    ('Mercedes Benz', 'GL 450', 'mercedes-benz', 'gl-450'),
    ('Mercedes Benz', 'GL 500', 'mercedes-benz', 'gl-500'),
    ('Mercedes Benz', 'GL 55 AMG', 'mercedes-benz', 'gl-55-amg'),
    ('Mercedes Benz', 'GL 63 AMG', 'mercedes-benz', 'gl-63-amg'),
    ('Mercedes Benz', 'GLA 180', 'mercedes-benz', 'gla-180'),
    ('Mercedes Benz', 'GLA 200', 'mercedes-benz', 'gla-200'),
    ('Mercedes Benz', 'GLA 220', 'mercedes-benz', 'gla-220'),
    ('Mercedes Benz', 'GLA 250', 'mercedes-benz', 'gla-250'),
    ('Mercedes Benz', 'GLA 35 AMG', 'mercedes-benz', 'gla-35-amg'),
    ('Mercedes Benz', 'GLA 45 AMG', 'mercedes-benz', 'gla-45-amg'),
    ('Mercedes Benz', 'GLB 180', 'mercedes-benz', 'glb-180'),
    ('Mercedes Benz', 'GLB 200', 'mercedes-benz', 'glb-200'),
    ('Mercedes Benz', 'GLB 220', 'mercedes-benz', 'glb-220'),
    ('Mercedes Benz', 'GLB 250', 'mercedes-benz', 'glb-250'),
    ('Mercedes Benz', 'GLB 35 AMG', 'mercedes-benz', 'glb-35-amg'),
    ('Mercedes Benz', 'GLC 200', 'mercedes-benz', 'glc-200'),
    ('Mercedes Benz', 'GLC 220', 'mercedes-benz', 'glc-220'),
    ('Mercedes Benz', 'GLC 250', 'mercedes-benz', 'glc-250'),
    ('Mercedes Benz', 'GLC 300', 'mercedes-benz', 'glc-300'),
    ('Mercedes Benz', 'GLC 350', 'mercedes-benz', 'glc-350'),
    ('Mercedes Benz', 'GLC 400', 'mercedes-benz', 'glc-400'),
    ('Mercedes Benz', 'GLC 43 AMG', 'mercedes-benz', 'glc-43-amg'),
    ('Mercedes Benz', 'GLC 63 AMG', 'mercedes-benz', 'glc-63-amg'),
    ('Mercedes Benz', 'GLE 250', 'mercedes-benz', 'gle-250'),
    ('Mercedes Benz', 'GLE 300', 'mercedes-benz', 'gle-300'),
    ('Mercedes Benz', 'GLE 350', 'mercedes-benz', 'gle-350'),
    ('Mercedes Benz', 'GLE 400', 'mercedes-benz', 'gle-400'),
    ('Mercedes Benz', 'GLE 43 AMG', 'mercedes-benz', 'gle-43-amg'),
    ('Mercedes Benz', 'GLE 450', 'mercedes-benz', 'gle-450'),
    ('Mercedes Benz', 'GLE 500', 'mercedes-benz', 'gle-500'),
    ('Mercedes Benz', 'GLE 53 AMG', 'mercedes-benz', 'gle-53-amg'),
    ('Mercedes Benz', 'GLE 580', 'mercedes-benz', 'gle-580'),
    ('Mercedes Benz', 'GLE 63 AMG', 'mercedes-benz', 'gle-63-amg'),
    ('Mercedes Benz', 'GLK 200', 'mercedes-benz', 'glk-200'),
    ('Mercedes Benz', 'GLK 220', 'mercedes-benz', 'glk-220'),
    ('Mercedes Benz', 'GLK 250', 'mercedes-benz', 'glk-250'),
    ('Mercedes Benz', 'GLK 280', 'mercedes-benz', 'glk-280'),
    ('Mercedes Benz', 'GLK 300', 'mercedes-benz', 'glk-300'),
    ('Mercedes Benz', 'GLK 320', 'mercedes-benz', 'glk-320'),
    ('Mercedes Benz', 'GLK 350', 'mercedes-benz', 'glk-350'),
    ('Mercedes Benz', 'GLS 350', 'mercedes-benz', 'gls-350'),
    ('Mercedes Benz', 'GLS 400', 'mercedes-benz', 'gls-400'),
    ('Mercedes Benz', 'GLS 450', 'mercedes-benz', 'gls-450'),
    ('Mercedes Benz', 'GLS 500', 'mercedes-benz', 'gls-500'),
    ('Mercedes Benz', 'GLS 580', 'mercedes-benz', 'gls-580'),
    ('Mercedes Benz', 'GLS 600', 'mercedes-benz', 'gls-600'),
    ('Mercedes Benz', 'GLS 63 AMG', 'mercedes-benz', 'gls-63-amg'),
    ('Mercedes Benz', 'Marco Polo', 'mercedes-benz', 'marco-polo'),
    ('Mercedes Benz', 'Maybach GLS', 'mercedes-benz', 'maybach-gls'),
    ('Mercedes Benz', 'Maybach S-Klasse', 'mercedes-benz', 'maybach-s-klasse'),
    ('Mercedes Benz', 'MB 100', 'mercedes-benz', 'mb-100'),
    ('Mercedes Benz', 'SL 230', 'mercedes-benz', 'sl-230'),
    ('Mercedes Benz', 'SL 250', 'mercedes-benz', 'sl-250'),
    ('Mercedes Benz', 'SL 300', 'mercedes-benz', 'sl-300'),
    ('Mercedes Benz', 'SL 320', 'mercedes-benz', 'sl-320'),
    ('Mercedes Benz', 'SL 350', 'mercedes-benz', 'sl-350'),
    ('Mercedes Benz', 'SL 380', 'mercedes-benz', 'sl-380'),
    ('Mercedes Benz', 'SL 400', 'mercedes-benz', 'sl-400'),
    ('Mercedes Benz', 'SL 420', 'mercedes-benz', 'sl-420'),
    ('Mercedes Benz', 'SL 43 AMG', 'mercedes-benz', 'sl-43-amg'),
    ('Mercedes Benz', 'SL 450', 'mercedes-benz', 'sl-450'),
    ('Mercedes Benz', 'SL 500', 'mercedes-benz', 'sl-500'),
    ('Mercedes Benz', 'SL 55 AMG', 'mercedes-benz', 'sl-55-amg'),
    ('Mercedes Benz', 'SL 560', 'mercedes-benz', 'sl-560'),
    ('Mercedes Benz', 'SL 60 AMG', 'mercedes-benz', 'sl-60-amg'),
    ('Mercedes Benz', 'SL 600', 'mercedes-benz', 'sl-600'),
    ('Mercedes Benz', 'SL 63 AMG', 'mercedes-benz', 'sl-63-amg'),
    ('Mercedes Benz', 'SL 65 AMG', 'mercedes-benz', 'sl-65-amg'),
    ('Mercedes Benz', 'SL 70 AMG', 'mercedes-benz', 'sl-70-amg'),
    ('Mercedes Benz', 'SL 73 AMG', 'mercedes-benz', 'sl-73-amg'),
    ('Mercedes Benz', 'SLC 180', 'mercedes-benz', 'slc-180'),
    ('Mercedes Benz', 'SLC 200', 'mercedes-benz', 'slc-200'),
    ('Mercedes Benz', 'SLC 250', 'mercedes-benz', 'slc-250'),
    ('Mercedes Benz', 'SLC 280', 'mercedes-benz', 'slc-280'),
    ('Mercedes Benz', 'SLC 300', 'mercedes-benz', 'slc-300'),
    ('Mercedes Benz', 'SLC 350', 'mercedes-benz', 'slc-350'),
    ('Mercedes Benz', 'SLC 380', 'mercedes-benz', 'slc-380'),
    ('Mercedes Benz', 'SLC 43 AMG', 'mercedes-benz', 'slc-43-amg'),
    ('Mercedes Benz', 'SLC 450', 'mercedes-benz', 'slc-450'),
    ('Mercedes Benz', 'SLC 500', 'mercedes-benz', 'slc-500'),
    ('Mercedes Benz', 'SLK', 'mercedes-benz', 'slk'),
    ('Mercedes Benz', 'SLK 200', 'mercedes-benz', 'slk-200'),
    ('Mercedes Benz', 'SLK 230', 'mercedes-benz', 'slk-230'),
    ('Mercedes Benz', 'SLK 250', 'mercedes-benz', 'slk-250'),
    ('Mercedes Benz', 'SLK 280', 'mercedes-benz', 'slk-280'),
    ('Mercedes Benz', 'SLK 300', 'mercedes-benz', 'slk-300'),
    ('Mercedes Benz', 'SLK 32 AMG', 'mercedes-benz', 'slk-32-amg'),
    ('Mercedes Benz', 'SLK 320', 'mercedes-benz', 'slk-320'),
    ('Mercedes Benz', 'SLK 350', 'mercedes-benz', 'slk-350'),
    ('Mercedes Benz', 'SLK 55 AMG', 'mercedes-benz', 'slk-55-amg'),
    ('Mercedes Benz', 'SLR', 'mercedes-benz', 'slr'),
    ('Mercedes Benz', 'SLS', 'mercedes-benz', 'sls'),
    ('Mercedes Benz', 'Sprinter', 'mercedes-benz', 'sprinter'),
    ('Mercedes Benz', 'T1', 'mercedes-benz', 't1'),
    ('Mercedes Benz', 'T2', 'mercedes-benz', 't2'),
    ('Mercedes Benz', 'Vaneo', 'mercedes-benz', 'vaneo'),
    ('Mercedes Benz', 'Vario', 'mercedes-benz', 'vario'),
    ('Mercedes Benz', 'Viano', 'mercedes-benz', 'viano'),
    ('Mercedes Benz', 'Vito', 'mercedes-benz', 'vito'),
    ('Mercedes Benz', 'W 114/115 Strich-Acht', 'mercedes-benz', 'w-114%2F115-strich-acht')
    


CREATE TABLE "mercedes_benz_car_prices_tbl" (
    "price_id" SERIAL NOT NULL,
    "make_and_model_id" INT,
    "year_id" INT,
    "colour_id" INT,
    "gear_id" INT,
    "fuel_type_id" INT,
    "km" INT,
    "kw" INT,
    "price" INT,
    CONSTRAINT "pk_mercedes_benz_car_prices_tbl" PRIMARY KEY (
        "price_id"
     )
);